/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-03-25 01:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.code.verse.entity.Message;

public final class login_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/normal_navBar.jsp", Long.valueOf(1742013754987L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.code.verse.entity.Message");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>login page</title>\r\n");
      out.write("\r\n");
      out.write("	<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("    integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"css/myStyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(" .primary_background {\r\n");
      out.write("  background-color: #00695f; /* Custom dark greenish-teal */\r\n");
      out.write("  color: black; }\r\n");
      out.write("\r\n");
      out.write("        .banner-background{\r\n");
      out.write("          clip-path: polygon(0 0, 100% 0, 100% 20%, 100% 86%, 68% 100%, 18% 93%, 0 100%, 0% 20%);\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("    <!-- navbar -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("  	<nav class=\"navbar navbar-expand-lg navbar-dark primary_background\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fa fa-hashtag\"></i> CodeVerse\r\n");
      out.write("    </a>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Toggler for mobile view -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("      aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar links -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("        <li class=\"nav-item active\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\"><i class=\"fa fa-bell\"></i> LearnCode</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- Dropdown Menu -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("            <i class=\"fa fa-check-square\"></i> Categories\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\"><i class=\"fa fa-code\"></i> Programming Languages</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\"><i class=\"fa fa-project-diagram\"></i> Project Implementation</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\"><i class=\"fa fa-database\"></i> Data Structures</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\"><i class=\"fa fa-user\"></i> Contact</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"login_page.jsp\"><i class=\"fa fa-user-circle fa-spin\"></i> Login</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"register_page.jsp\"><i class=\"fa fa-user-plus fa-spin\"></i> Signup</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- Search Bar -->\r\n");
      out.write("      <form class=\"d-flex\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<main class=\"d-flex align-items-center primary_background banner-background\" style=\"height:90vh\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		    <div class=\"row\">\r\n");
      out.write("		    	<div class=\"col-md-4 offset-md-4\">\r\n");
      out.write("		    		<div class=\"card\">\r\n");
      out.write("		    			<div class=\"card-header primary_background text-white text-center\">\r\n");
      out.write("		 		    			<span class=\"fa fa-user-circle fa-3x\"></span>\r\n");
      out.write("		 		    			<p>Login here</p>\r\n");
      out.write("		    			</div>\r\n");
      out.write("		    			");

		    			 	Message m=(Message)session.getAttribute("msg");
		    				if(m != null){
		    			
      out.write("\r\n");
      out.write("		    			<div class=\"alert ");
      out.print( m.getCssClass() );
      out.write("\" role=\"alert\">\r\n");
      out.write("  							");
      out.print( m.getContent() );
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("		    			");

		    				session.removeAttribute("msg");
		    				}
		    			
      out.write("\r\n");
      out.write("		    			 <div class=\"card-body\">\r\n");
      out.write("		    				<form action=\"login\" method=\"post\">\r\n");
      out.write("							  <div class=\"form-group\">\r\n");
      out.write("							    <label for=\"exampleInputEmail1\">Email address</label>\r\n");
      out.write("							    <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" name=\"email\">\r\n");
      out.write("							    <small id=\"emailHelp\" class=\"form-text text-muted\">We'll never share your email with anyone else.</small>\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <div class=\"form-group\">\r\n");
      out.write("							    <label for=\"exampleInputPassword1\">Password</label>\r\n");
      out.write("							    <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\"  name=\"password\">\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <div class=\"form-group form-check\">\r\n");
      out.write("							    <input type=\"checkbox\" class=\"form-check-input\" id=\"exampleCheck1\">\r\n");
      out.write("							    <label class=\"form-check-label\" for=\"exampleCheck1\">Remember me</label>\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <button type=\"submit\" class=\"btn btn-primary\">login</button>\r\n");
      out.write("							</form>\r\n");
      out.write("		    		\r\n");
      out.write("		    		    </div>\r\n");
      out.write("		    		</div>\r\n");
      out.write("		    	</div>\r\n");
      out.write("		    \r\n");
      out.write("		    </div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScripts -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("        integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("        src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("        src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
